sudo: required
services:
  - docker

before_install:
  - docker build -t touchthesun/docker-front -f Dockerfile.dev .

script:
  - docker run -e CI=true touchthesun/docker-front npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-front"
  env: "DockerFront-env"
  bucket_name: "elasticbeanstalk-us-east-1-891777308283"
  bucket_path: "docker-front"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
